// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFjlLMKo4xe9a8OYO5i58xtkmguQfF9s',
    appId: '1:182284059770:web:29928a4843331a9e4567c3',
    messagingSenderId: '182284059770',
    projectId: 'memoryapp-74734',
    authDomain: 'memoryapp-74734.firebaseapp.com',
    storageBucket: 'memoryapp-74734.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPq_gbpm3OiYhxasQBOJYnnyWSiSYK4Pc',
    appId: '1:182284059770:android:2c09c60c10af4bc04567c3',
    messagingSenderId: '182284059770',
    projectId: 'memoryapp-74734',
    storageBucket: 'memoryapp-74734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKD-BOcKOp8LNCLb_6z4Jdq8NurHcp_M',
    appId: '1:182284059770:ios:e332e243699a2dc74567c3',
    messagingSenderId: '182284059770',
    projectId: 'memoryapp-74734',
    storageBucket: 'memoryapp-74734.appspot.com',
    iosBundleId: 'com.example.memoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKD-BOcKOp8LNCLb_6z4Jdq8NurHcp_M',
    appId: '1:182284059770:ios:e332e243699a2dc74567c3',
    messagingSenderId: '182284059770',
    projectId: 'memoryapp-74734',
    storageBucket: 'memoryapp-74734.appspot.com',
    iosBundleId: 'com.example.memoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdFjlLMKo4xe9a8OYO5i58xtkmguQfF9s',
    appId: '1:182284059770:web:0df2bc4fdd6233fe4567c3',
    messagingSenderId: '182284059770',
    projectId: 'memoryapp-74734',
    authDomain: 'memoryapp-74734.firebaseapp.com',
    storageBucket: 'memoryapp-74734.appspot.com',
  );
}
